import type {
  ClubConfig,
  TeamMember,
  Event,
  Announcement,
  Thread,
  Chatroom,
  ChatMessage,
  User,
} from '../types/api'

export const INITIAL_USERS: User[] = [
  {
    id: 1,
    username: 'rudraj',
    name: 'Rudra Joshi',
    email: 'rudra@forge.club',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80',
    bio: 'Founder & President @ Forge. Backend engineer passionate about systems design and distributed computing.',
  },
  {
    id: 2,
    username: 'arjunm',
    name: 'Arjun Mehta',
    email: 'arjun@forge.club',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&auto=format&fit=crop&q=80',
    bio: 'Vice President @ Forge. Full-stack developer with a keen eye for UI/UX and design systems.',
  },
  {
    id: 3,
    username: 'priyasharma',
    name: 'Priya Sharma',
    email: 'priya@forge.club',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&auto=format&fit=crop&q=80',
    bio: 'Design Lead @ Forge. Turning complex technical workflows into delightful, accessible interfaces.',
  },
  {
    id: 4,
    username: 'karansingh',
    name: 'Karan Singh',
    email: 'karan@forge.club',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&auto=format&fit=crop&q=80',
    bio: 'Tech Lead @ Forge. Cloud-native enthusiast, Kubernetes wrangler, and open source builder.',
  },
  {
    id: 5,
    username: 'guest_builder',
    name: 'Guest Builder',
    email: 'guest@forge.club',
    avatar: '',
    bio: 'Explorer and software enthusiast tinkering with React, Go, and AI agents.',
  },
]

export const INITIAL_CLUB_CONFIG: ClubConfig = {
  id: 1,
  name: 'Forge',
  tagline: 'Where Builders Unite',
  description: "We're a college tech club. We build stuff, break stuff, and occasionally ship stuff. If you like making things with code or design, you'll fit right in here.",
  logo_url: '/Devign logo v1 pngV.png',
  hero_image_url: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=1200&auto=format&fit=crop&q=80',
  social_links: {
    github: 'https://github.com',
    discord: 'https://discord.com',
    twitter: 'https://twitter.com',
    linkedin: 'https://linkedin.com',
    instagram: 'https://instagram.com',
  },
  founding_year: 2024,
  contact_email: 'hello@forge.club',
  created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 365).toISOString(),
  updated_at: new Date().toISOString(),
}

export const INITIAL_TEAM: TeamMember[] = [
  {
    id: 1,
    name: 'Rudra Joshi',
    role: 'Founder & President',
    bio: 'Backend engineer passionate about systems design, distributed computing, and building tools developers love.',
    avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80',
    social_links: {
      github: 'https://github.com',
      linkedin: 'https://linkedin.com',
    },
    display_order: 1,
    is_active: true,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 300).toISOString(),
  },
  {
    id: 2,
    name: 'Arjun Mehta',
    role: 'Vice President',
    bio: 'Full-stack developer with a keen eye for UX. Leads frontend architecture and design system engineering.',
    avatar_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&auto=format&fit=crop&q=80',
    social_links: {
      github: 'https://github.com',
      twitter: 'https://twitter.com',
    },
    display_order: 2,
    is_active: true,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 280).toISOString(),
  },
  {
    id: 3,
    name: 'Priya Sharma',
    role: 'Design Lead',
    bio: 'UI/UX designer turning complex workflows into intuitive interfaces. Advocates for accessibility-first design.',
    avatar_url: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&auto=format&fit=crop&q=80',
    social_links: {
      linkedin: 'https://linkedin.com',
      instagram: 'https://instagram.com',
    },
    display_order: 3,
    is_active: true,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 250).toISOString(),
  },
  {
    id: 4,
    name: 'Karan Singh',
    role: 'Tech Lead',
    bio: 'Cloud-native enthusiast. Builds scalable backends and manages our core deployment infrastructure.',
    avatar_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&auto=format&fit=crop&q=80',
    social_links: {
      github: 'https://github.com',
    },
    display_order: 4,
    is_active: true,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 220).toISOString(),
  },
  {
    id: 5,
    name: 'Ananya Patel',
    role: 'Events Coordinator',
    bio: 'Organizes hackathons, workshops, and speaker sessions. Makes sure every club event is unforgettable.',
    avatar_url: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=400&auto=format&fit=crop&q=80',
    social_links: {
      instagram: 'https://instagram.com',
    },
    display_order: 5,
    is_active: true,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 200).toISOString(),
  },
  {
    id: 6,
    name: 'Vikram Rao',
    role: 'Community Manager',
    bio: 'Open-source contributor and community builder. Manages our Discord, socials, and member outreach.',
    avatar_url: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=400&auto=format&fit=crop&q=80',
    social_links: {
      github: 'https://github.com',
      discord: 'https://discord.com',
    },
    display_order: 6,
    is_active: true,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 180).toISOString(),
  },
]

const now = new Date()

export const INITIAL_EVENTS: Event[] = [
  {
    id: 1,
    title: 'Design Systems Workshop',
    description: "Learn to build scalable design systems from scratch. We'll cover tokens, component APIs, theming, and bridging the gap between Figma and code.",
    date: new Date(now.getTime() + 1000 * 60 * 60 * 24 * 14).toISOString(),
    location: 'Room 302, CS Building',
    event_type: 'workshop',
    status: 'upcoming',
    image_url: 'https://images.unsplash.com/photo-1581291518857-4e27b48ff24e?w=800&auto=format&fit=crop&q=80',
    registration_link: 'https://forge.club/events/design-systems',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 2,
    title: "Forge Hackathon '26",
    description: '48-hour hackathon where design meets code. Teams of 3–4 build a product from concept to MVP. Prizes, mentors, and lots of coffee.',
    date: new Date(now.getTime() + 1000 * 60 * 60 * 24 * 30).toISOString(),
    end_date: new Date(now.getTime() + 1000 * 60 * 60 * 24 * 32).toISOString(),
    location: 'Innovation Hub, Main Campus',
    event_type: 'hackathon',
    status: 'upcoming',
    image_url: 'https://images.unsplash.com/photo-1504384308090-c894fdcc538d?w=800&auto=format&fit=crop&q=80',
    registration_link: 'https://forge.club/events/hackathon-26',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 3,
    title: 'Tech Talk: Building at Scale',
    description: 'Industry guest speaker on scaling distributed systems in production environments. Interactive Q&A included.',
    date: new Date(now.getTime() + 1000 * 60 * 60 * 24 * 21).toISOString(),
    location: 'Auditorium B',
    event_type: 'talk',
    status: 'upcoming',
    image_url: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=800&auto=format&fit=crop&q=80',
    registration_link: 'https://forge.club/events/tech-talk-scale',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 4,
    title: 'Weekly Standup & Code Review',
    description: 'Our open weekly session where members demo what they have built, receive code reviews, and collaborate on club projects.',
    date: new Date(now.getTime() + 1000 * 60 * 60 * 24 * 7).toISOString(),
    location: 'Forge HQ (Room 118)',
    event_type: 'meetup',
    status: 'upcoming',
    image_url: 'https://images.unsplash.com/photo-1531403009284-440f080d1e12?w=800&auto=format&fit=crop&q=80',
    registration_link: 'https://forge.club/events/weekly-standup',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
]

export const INITIAL_ANNOUNCEMENTS: Announcement[] = [
  {
    id: 1,
    title: 'The Forge Platform is Live',
    content: "We've officially launched the new Forge community workspace. Forum, live chat, and event updates are now unified in one spot. Feel free to explore and build together!",
    priority: 'high',
    is_pinned: true,
    author_id: 1,
    author: INITIAL_USERS[0],
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2).toISOString(),
    updated_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2).toISOString(),
  },
  {
    id: 2,
    title: "Hackathon '26 Registrations are Open",
    content: "Teams of 3–4 can now register for the Forge Hackathon '26. Spots are limited, so confirm your team roster soon!",
    priority: 'urgent',
    is_pinned: true,
    author_id: 2,
    author: INITIAL_USERS[1],
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 5).toISOString(),
    updated_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 5).toISOString(),
  },
  {
    id: 3,
    title: 'Design System RFC & Open Review',
    content: 'Our UI component library RFC is open for community feedback. Head over to the forum thread to share your thoughts on token names and Radix primitives.',
    priority: 'normal',
    is_pinned: false,
    author_id: 3,
    author: INITIAL_USERS[2],
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 8).toISOString(),
    updated_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 8).toISOString(),
  },
]

export const INITIAL_THREADS: Thread[] = [
  {
    id: 1,
    title: 'Architecting a Multi-Tenant Microservice with Go and gRPC',
    user_id: 1,
    user: INITIAL_USERS[0],
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 18).toISOString(),
    updated_at: new Date(Date.now() - 1000 * 60 * 60 * 18).toISOString(),
    images: [
      {
        id: 1,
        thread_id: 1,
        url: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=800&auto=format&fit=crop&q=80',
        caption: 'Microservices architecture diagram',
      },
    ],
    reactions: [
      { id: 1, thread_id: 1, user_id: 2, user: INITIAL_USERS[1], emoji: '🔥', created_at: new Date().toISOString() },
      { id: 2, thread_id: 1, user_id: 3, user: INITIAL_USERS[2], emoji: '❤️', created_at: new Date().toISOString() },
      { id: 3, thread_id: 1, user_id: 4, user: INITIAL_USERS[3], emoji: '👍', created_at: new Date().toISOString() },
    ],
    posts: [
      {
        id: 1,
        content: 'Sharing our learnings from migrating from a monolith to distributed gRPC services. We saw a 4x reduction in response latency and streamlined our service boundaries. What is your preferred communication protocol for internal services?',
        thread_id: 1,
        user_id: 1,
        user: INITIAL_USERS[0],
        created_at: new Date(Date.now() - 1000 * 60 * 60 * 18).toISOString(),
        updated_at: new Date(Date.now() - 1000 * 60 * 60 * 18).toISOString(),
      },
      {
        id: 2,
        content: 'Great writeup! Did you benchmark proto serialization overhead against JSON over HTTP/2 for smaller payloads? Curious about how you handle distributed tracing across services.',
        thread_id: 1,
        user_id: 2,
        user: INITIAL_USERS[1],
        created_at: new Date(Date.now() - 1000 * 60 * 60 * 12).toISOString(),
        updated_at: new Date(Date.now() - 1000 * 60 * 60 * 12).toISOString(),
      },
      {
        id: 3,
        content: 'We use OpenTelemetry with Jaeger collectors injected as sidecars in Kubernetes. It integrates smoothly with gRPC interceptors in Go!',
        thread_id: 1,
        user_id: 4,
        user: INITIAL_USERS[3],
        created_at: new Date(Date.now() - 1000 * 60 * 60 * 6).toISOString(),
        updated_at: new Date(Date.now() - 1000 * 60 * 60 * 6).toISOString(),
      },
    ],
  },
  {
    id: 2,
    title: 'Showcase: Modern Component Library built with Radix & TailwindCSS v4',
    user_id: 3,
    user: INITIAL_USERS[2],
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 36).toISOString(),
    updated_at: new Date(Date.now() - 1000 * 60 * 60 * 36).toISOString(),
    images: [
      {
        id: 2,
        thread_id: 2,
        url: 'https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?w=800&auto=format&fit=crop&q=80',
        caption: 'UI component playground preview',
      },
    ],
    reactions: [
      { id: 4, thread_id: 2, user_id: 1, user: INITIAL_USERS[0], emoji: '🎉', created_at: new Date().toISOString() },
      { id: 5, thread_id: 2, user_id: 2, user: INITIAL_USERS[1], emoji: '❤️', created_at: new Date().toISOString() },
    ],
    posts: [
      {
        id: 4,
        content: "Here is a preview of the new UI components designed for the Forge club ecosystem. Every primitive is fully keyboard navigable, accessible, and easily themeable. Let us know what components you'd like to see next!",
        thread_id: 2,
        user_id: 3,
        user: INITIAL_USERS[2],
        created_at: new Date(Date.now() - 1000 * 60 * 60 * 36).toISOString(),
        updated_at: new Date(Date.now() - 1000 * 60 * 60 * 36).toISOString(),
      },
      {
        id: 5,
        content: 'The animation transitions and focus rings look super crisp. Great work!',
        thread_id: 2,
        user_id: 1,
        user: INITIAL_USERS[0],
        created_at: new Date(Date.now() - 1000 * 60 * 60 * 20).toISOString(),
        updated_at: new Date(Date.now() - 1000 * 60 * 60 * 20).toISOString(),
      },
    ],
  },
  {
    id: 3,
    title: 'Best practices for Dockerizing Vite React apps with Multi-Stage Builds',
    user_id: 4,
    user: INITIAL_USERS[3],
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 50).toISOString(),
    updated_at: new Date(Date.now() - 1000 * 60 * 60 * 50).toISOString(),
    images: [],
    reactions: [
      { id: 6, thread_id: 3, user_id: 2, user: INITIAL_USERS[1], emoji: '👍', created_at: new Date().toISOString() },
    ],
    posts: [
      {
        id: 6,
        content: 'Quick guide on creating ultra-slim Nginx production containers for SPA builds. We were able to reduce image sizes from ~450MB down to under 25MB using alpine-based multistage Dockerfiles.',
        thread_id: 3,
        user_id: 4,
        user: INITIAL_USERS[3],
        created_at: new Date(Date.now() - 1000 * 60 * 60 * 50).toISOString(),
        updated_at: new Date(Date.now() - 1000 * 60 * 60 * 50).toISOString(),
      },
    ],
  },
]

export const INITIAL_CHATROOMS: Chatroom[] = [
  {
    id: 1,
    name: 'general',
    description: 'General discussion for Forge members and developers',
    created_by: 1,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 60).toISOString(),
    active_users: 8,
  },
  {
    id: 2,
    name: 'projects-showcase',
    description: 'Share what you are currently building and get feedback',
    created_by: 2,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 45).toISOString(),
    active_users: 5,
  },
  {
    id: 3,
    name: 'hackathon-prep',
    description: 'Teaming up and ideation for upcoming hackathons',
    created_by: 1,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 30).toISOString(),
    active_users: 12,
  },
  {
    id: 4,
    name: 'help-desk',
    description: 'Debug code, ask syntax questions, and get assistance',
    created_by: 4,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 20).toISOString(),
    active_users: 3,
  },
]

export const INITIAL_CHAT_MESSAGES: Record<number, ChatMessage[]> = {
  1: [
    {
      id: 101,
      chatroom_id: 1,
      user_id: 1,
      user: INITIAL_USERS[0],
      content: 'Hey everyone! Welcome to the Forge general channel 🚀',
      created_at: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
      reactions: [],
    },
    {
      id: 102,
      chatroom_id: 1,
      user_id: 2,
      user: INITIAL_USERS[1],
      content: 'Awesome! Glad to see the workspace live and running.',
      created_at: new Date(Date.now() - 1000 * 60 * 55).toISOString(),
      reactions: [],
    },
    {
      id: 103,
      chatroom_id: 1,
      user_id: 3,
      user: INITIAL_USERS[2],
      content: 'Dont forget to check out the upcoming Design Systems workshop next week!',
      created_at: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
      reactions: [],
    },
    {
      id: 104,
      chatroom_id: 1,
      user_id: 4,
      user: INITIAL_USERS[3],
      content: 'Ready to build some great projects together 💻',
      created_at: new Date(Date.now() - 1000 * 60 * 5).toISOString(),
      reactions: [],
    },
  ],
  2: [
    {
      id: 201,
      chatroom_id: 2,
      user_id: 2,
      user: INITIAL_USERS[1],
      content: 'Drop links to your repos or Figma mockups here for peer review!',
      created_at: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
      reactions: [],
    },
  ],
  3: [
    {
      id: 301,
      chatroom_id: 3,
      user_id: 1,
      user: INITIAL_USERS[0],
      content: "Who's looking for teammates for Forge Hackathon '26? Looking for 1 frontend dev and 1 designer.",
      created_at: new Date(Date.now() - 1000 * 60 * 90).toISOString(),
      reactions: [],
    },
  ],
  4: [
    {
      id: 401,
      chatroom_id: 4,
      user_id: 4,
      user: INITIAL_USERS[3],
      content: 'Have a bug in your React, Go, or Python setup? Paste your snippet here.',
      created_at: new Date(Date.now() - 1000 * 60 * 150).toISOString(),
      reactions: [],
    },
  ],
}
