import type {
  ClubConfig,
  TeamMember,
  Event,
  Announcement,
  Achievement,
  Thread,
  Chatroom,
  ChatMessage,
  User,
} from '../types/api'

export const INITIAL_USERS: User[] = [
  {
    id: 1,
    username: 'prasthanam_lead',
    name: 'Vaibhav Pokhriyal',
    email: 'lead@prasthanam.gbpiet.ac.in',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80',
    bio: 'Lead @ Prasthanam Robotics Club, GBPIET. Robotics engineer passionate about embedded systems, ROS, and combat robotics.',
  },
  {
    id: 2,
    username: 'robowar_tech',
    name: 'Aditya Rawat',
    email: 'aditya@prasthanam.gbpiet.ac.in',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&auto=format&fit=crop&q=80',
    bio: 'Hardware & Combat Robotics Lead. Specializes in brushless motor drivers, pneumatic flippers, and CAD chassis design.',
  },
  {
    id: 3,
    username: 'drone_embedded',
    name: 'Neha Negi',
    email: 'neha@prasthanam.gbpiet.ac.in',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&auto=format&fit=crop&q=80',
    bio: 'Autonomous Systems & Drone Lead. Working on PX4 flight controllers, Computer Vision, and LiDAR obstacle mapping.',
  },
  {
    id: 4,
    username: 'iot_automation',
    name: 'Siddharth Joshi',
    email: 'siddharth@prasthanam.gbpiet.ac.in',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&auto=format&fit=crop&q=80',
    bio: 'Embedded Firmware & IoT Lead. STM32, Arduino, ESP32, and custom PCB designer.',
  },
  {
    id: 5,
    username: 'robotics_enthusiast',
    name: 'Prasthanam Member',
    email: 'member@prasthanam.gbpiet.ac.in',
    avatar: '',
    bio: 'GBPIET Robotics explorer exploring microcontrollers, ROS2, and line followers.',
  },
]

export const INITIAL_CLUB_CONFIG: ClubConfig = {
  id: 1,
  name: 'Prasthanam',
  tagline: 'The Robotics Club of GBPIET',
  description: "Prasthanam Robotics Club, founded in 2022, is more than a robotics community—it's a journey of ambition, innovation, and perseverance. Every robot built, every challenge overcome, and every achievement earned reflects the dedication of our students. United by curiosity and driven by excellence, we continue to learn, create, and lead the way toward a smarter future.",
  logo_url: '/new-logo.png',
  hero_image_url: 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=1200&auto=format&fit=crop&q=80',
  social_links: {
    github: 'https://github.com/prasthanam-gbpiet',
    instagram: 'https://instagram.com/prasthanam_gbpiet',
    linkedin: 'https://linkedin.com/company/prasthanam-gbpiet',
    youtube: 'https://youtube.com',
  },
  founding_year: 2022,
  contact_email: 'prasthanam@gbpiet.ac.in',
  created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 365 * 2).toISOString(),
  updated_at: new Date().toISOString(),
}

export const INITIAL_TEAM: TeamMember[] = [
  {
    id: 1,
    name: 'Uday Pant',
    role: 'Final Year',
    bio: 'Specializing in robotics system architecture, embedded controls, and autonomous navigation.',
    avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80',
    social_links: {
      github: 'https://github.com',
      linkedin: 'https://linkedin.com',
    },
    display_order: 1,
    is_active: true,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 365).toISOString(),
  },
  {
    id: 2,
    name: 'Pranjul',
    role: 'Final Year',
    bio: 'Combat robotics design, structural fabrication, CAD modeling, and high-torque drivetrain systems.',
    avatar_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&auto=format&fit=crop&q=80',
    social_links: {
      github: 'https://github.com',
      linkedin: 'https://linkedin.com',
    },
    display_order: 2,
    is_active: true,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 350).toISOString(),
  },
  {
    id: 3,
    name: 'Vaibhav Pokhriyal',
    role: 'Third Year',
    bio: 'Embedded systems development, ROS2 navigation, microcontrollers, and autonomous rover locomotion.',
    avatar_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&auto=format&fit=crop&q=80',
    social_links: {
      github: 'https://github.com',
      linkedin: 'https://linkedin.com',
    },
    display_order: 3,
    is_active: true,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 300).toISOString(),
  },
  {
    id: 4,
    name: 'Rahul Joshi',
    role: 'Third Year',
    bio: 'Embedded firmware programming, sensor interfacing, and hardware circuit prototyping.',
    avatar_url: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=400&auto=format&fit=crop&q=80',
    social_links: {
      github: 'https://github.com',
      linkedin: 'https://linkedin.com',
    },
    display_order: 4,
    is_active: true,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 280).toISOString(),
  },
  {
    id: 5,
    name: 'Priyanshu Shah',
    role: 'Third Year',
    bio: 'CAD modeling, 3D printing, chassis mechanics, and combat bot arena testing.',
    avatar_url: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400&auto=format&fit=crop&q=80',
    social_links: {
      github: 'https://github.com',
      linkedin: 'https://linkedin.com',
    },
    display_order: 5,
    is_active: true,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 260).toISOString(),
  },
  {
    id: 6,
    name: 'Ayush Dilwan',
    role: 'Third Year',
    bio: 'Power distribution boards, brushless motor ESCs, and wireless telemetry communication.',
    avatar_url: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=400&auto=format&fit=crop&q=80',
    social_links: {
      github: 'https://github.com',
      linkedin: 'https://linkedin.com',
    },
    display_order: 6,
    is_active: true,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 240).toISOString(),
  },
  {
    id: 7,
    name: 'Adarsh',
    role: 'Third Year',
    bio: 'Autonomous path planning, line followers, obstacle avoidance, and sensor fusion algorithms.',
    avatar_url: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=400&auto=format&fit=crop&q=80',
    social_links: {
      github: 'https://github.com',
      linkedin: 'https://linkedin.com',
    },
    display_order: 7,
    is_active: true,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 220).toISOString(),
  },
  {
    id: 8,
    name: 'Yash Saini',
    role: 'Third Year',
    bio: 'Computer vision, OpenCV object tracking, and robotic manipulator kinematics.',
    avatar_url: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=400&auto=format&fit=crop&q=80',
    social_links: {
      github: 'https://github.com',
      linkedin: 'https://linkedin.com',
    },
    display_order: 8,
    is_active: true,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 200).toISOString(),
  },
  {
    id: 9,
    name: 'Priyanshu Nautiyal',
    role: 'Third Year',
    bio: 'Drone flight dynamics, PX4 autopilot controllers, and aerial telemetry systems.',
    avatar_url: 'https://images.unsplash.com/photo-1501196354995-cbb51c65aaea?w=400&auto=format&fit=crop&q=80',
    social_links: {
      github: 'https://github.com',
      linkedin: 'https://linkedin.com',
    },
    display_order: 9,
    is_active: true,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 180).toISOString(),
  },
  {
    id: 10,
    name: 'Priya Maurya',
    role: 'Third Year',
    bio: 'IoT automation, embedded logic, and event coordination for club robotics workshops.',
    avatar_url: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&auto=format&fit=crop&q=80',
    social_links: {
      github: 'https://github.com',
      linkedin: 'https://linkedin.com',
    },
    display_order: 10,
    is_active: true,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 160).toISOString(),
  },
  {
    id: 11,
    name: 'Khushi Arya',
    role: 'Third Year',
    bio: 'Circuit schematic design, microcontroller programming, and technical project documentation.',
    avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80',
    social_links: {
      github: 'https://github.com',
      linkedin: 'https://linkedin.com',
    },
    display_order: 11,
    is_active: true,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 140).toISOString(),
  },
  {
    id: 12,
    name: 'Rishika',
    role: 'Third Year',
    bio: 'Robotics community initiatives, hackathon technical prep, and embedded problem solving.',
    avatar_url: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=400&auto=format&fit=crop&q=80',
    social_links: {
      github: 'https://github.com',
      linkedin: 'https://linkedin.com',
    },
    display_order: 12,
    is_active: true,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 120).toISOString(),
  },
]

const now = new Date()

export const INITIAL_EVENTS: Event[] = [
  {
    id: 1,
    title: 'Prasthanam Robowars League 2026',
    description: 'The flagship annual combat robotics clash at GBPIET. 15kg & 30kg combat bots battle it out in a reinforced steel arena. Featuring spinners, flippers, and wedge bots.',
    date: new Date(now.getTime() + 1000 * 60 * 60 * 24 * 14).toISOString(),
    location: 'Main College Arena, GBPIET',
    event_type: 'competition',
    status: 'upcoming',
    image_url: 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=800&auto=format&fit=crop&q=80',
    registration_link: 'https://prasthanam.gbpiet.ac.in/events/robowars-26',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 2,
    title: 'Autonomous Line Follower & Maze Solver Championship',
    description: 'High-speed PID-controlled autonomous robots race through intricate track curves, inverted intersections, and dynamic grid mazes.',
    date: new Date(now.getTime() + 1000 * 60 * 60 * 24 * 28).toISOString(),
    location: 'Mechanical Dept Hall, GBPIET',
    event_type: 'competition',
    status: 'upcoming',
    image_url: 'https://images.unsplash.com/photo-1563770660941-20978e870e26?w=800&auto=format&fit=crop&q=80',
    registration_link: 'https://prasthanam.gbpiet.ac.in/events/line-follower',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 3,
    title: 'Hands-on Drone Aerodynamics & Flight Controller Workshop',
    description: 'Build your own quadcopter from components. Learn PID tuning on Betaflight/ArduPilot, radio telemetry, and optical flow navigation.',
    date: new Date(now.getTime() + 1000 * 60 * 60 * 24 * 40).toISOString(),
    location: 'Robotics Innovation Lab (Room 204)',
    event_type: 'workshop',
    status: 'upcoming',
    image_url: 'https://images.unsplash.com/photo-1508614589041-895b88991e3e?w=800&auto=format&fit=crop&q=80',
    registration_link: 'https://prasthanam.gbpiet.ac.in/events/drone-workshop',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 4,
    title: 'Arduino, STM32 & ROS2 Micro-Controller Bootcamp',
    description: '3-day zero-to-hero bootcamp covering sensor interfacing, motor drivers, PWM control, I2C/SPI protocols, and ROS2 robot nodes.',
    date: new Date(now.getTime() + 1000 * 60 * 60 * 24 * 55).toISOString(),
    location: 'Auditorium C, GBPIET',
    event_type: 'workshop',
    status: 'upcoming',
    image_url: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=800&auto=format&fit=crop&q=80',
    registration_link: 'https://prasthanam.gbpiet.ac.in/events/ros-bootcamp',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
]

export const INITIAL_ACHIEVEMENTS: Achievement[] = [
  {
    id: 1,
    title: '1st Place Champions - National Robowars Championship',
    competition: 'National Technical Symposium 2025',
    year: '2025',
    rank: '1st Place 🏆',
    category: 'Combat Robotics (15kg Category)',
    description: 'Our custom drum-spinner bot "Vajra" undefeated throughout 6 tournament rounds, winning 1st place with total arena dominance.',
    image_url: 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=800&auto=format&fit=crop&q=80',
    badge: 'National Champion',
  },
  {
    id: 2,
    title: 'Gold Medal - Autonomous Line Follower & Maze Solver',
    competition: 'Inter-College Robotics Fest',
    year: '2025',
    rank: 'Gold Medal 🥇',
    category: 'Autonomous Navigation',
    description: 'Custom PID tuned high-speed line tracker clocked an astonishing 8.42s track completion time, setting a new record.',
    image_url: 'https://images.unsplash.com/photo-1563770660941-20978e870e26?w=800&auto=format&fit=crop&q=80',
    badge: 'Track Record',
  },
  {
    id: 3,
    title: 'Grand Finalists - Smart India Hackathon (SIH)',
    competition: 'Smart India Hackathon (Hardware Edition)',
    year: '2024',
    rank: 'Top 5 Finalists 🚀',
    category: 'Disaster Robotics & AI',
    description: 'Designed an all-terrain amphibious surveillance rover with gas sensors, thermal cameras, and mesh communication for flood rescue.',
    image_url: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=800&auto=format&fit=crop&q=80',
    badge: 'National Finalist',
  },
  {
    id: 4,
    title: 'Best Innovation & Design Award - Bionic Robotic Arm',
    competition: 'State Tech Expo Uttarakhand',
    year: '2024',
    rank: 'Best Innovation 🏅',
    category: 'Bio-Mechatronics',
    description: 'Developed an EMG muscle-signal controlled 5-degree-of-freedom 3D printed prosthetic arm with tactile pressure feedback.',
    image_url: 'https://images.unsplash.com/photo-1531403009284-440f080d1e12?w=800&auto=format&fit=crop&q=80',
    badge: 'Innovation Award',
  },
  {
    id: 5,
    title: '2nd Runner Up - All-India Robo-Soccer Cup',
    competition: 'Techfest North India',
    year: '2024',
    rank: '2nd Runner Up 🥉',
    category: 'Wireless Remote Robotics',
    description: 'Omni-wheel drive robotic striker and goalkeeper built with dual high-speed micro-metal gearmotors and RF remote link.',
    image_url: 'https://images.unsplash.com/photo-1508614589041-895b88991e3e?w=800&auto=format&fit=crop&q=80',
    badge: 'Podium Finish',
  },
  {
    id: 6,
    title: '15+ Combat & Autonomous Robots Fabricated',
    competition: 'Prasthanam Innovation Lab',
    year: '2023 - 2026',
    rank: 'Milestone ⚡',
    category: 'Club Research & Mentorship',
    description: 'Over 600+ GBPIET students trained in microcontroller programming, solidworks CAD design, soldering, and drone piloting.',
    image_url: 'https://images.unsplash.com/photo-1581291518857-4e27b48ff24e?w=800&auto=format&fit=crop&q=80',
    badge: '600+ Members',
  },
]

export const INITIAL_ANNOUNCEMENTS: Announcement[] = [
  {
    id: 1,
    title: 'Prasthanam Robotics Lab is Open for Club Projects',
    content: "The robotics innovation lab in GBPIET (Room 204) is fully equipped with 3D printers, soldering stations, oscilloscope, and microcontroller testing kits. Drop by during lab hours to build your bot!",
    priority: 'high',
    is_pinned: true,
    author_id: 1,
    author: INITIAL_USERS[0],
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2).toISOString(),
    updated_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2).toISOString(),
  },
  {
    id: 2,
    title: "Registrations Open for Robowars League '26",
    content: "Team registrations for the 15kg lightweight and featherweight combat categories are now live. Register your team and submit your bot CAD specifications before the deadline. Meet scheduled on: 23rd August, 25th August, 30th August, 6th September, 20th September, 29th September, 9th October.",
    priority: 'urgent',
    is_pinned: true,
    author_id: 2,
    author: INITIAL_USERS[1],
    registration_link: 'https://prasthanam.gbpiet.ac.in/events/robowars-26',
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 5).toISOString(),
    updated_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 5).toISOString(),
  },
  {
    id: 3,
    title: 'New Drone Telemetry & ROS2 Workshop Coming Up',
    content: 'We are organizing an intensive weekend hands-on session on ROS2 node architecture, Gazebo simulation, and autonomous waypoint tracking for quadcopters.',
    priority: 'normal',
    is_pinned: false,
    author_id: 3,
    author: INITIAL_USERS[2],
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 8).toISOString(),
    updated_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 8).toISOString(),
  },
]

export const INITIAL_THREADS: Thread[] = [
  {
    id: 1,
    title: 'Designing High-Torque Brushless ESCs for 15kg Combat Spinners',
    user_id: 2,
    user: INITIAL_USERS[1],
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 18).toISOString(),
    updated_at: new Date(Date.now() - 1000 * 60 * 60 * 18).toISOString(),
    images: [
      {
        id: 1,
        thread_id: 1,
        url: 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=800&auto=format&fit=crop&q=80',
        caption: 'Combat drum spinner test bench assembly',
      },
    ],
    reactions: [
      { id: 1, thread_id: 1, user_id: 1, user: INITIAL_USERS[0], emoji: '🔥', created_at: new Date().toISOString() },
      { id: 2, thread_id: 1, user_id: 3, user: INITIAL_USERS[2], emoji: '❤️', created_at: new Date().toISOString() },
      { id: 3, thread_id: 1, user_id: 4, user: INITIAL_USERS[3], emoji: '👍', created_at: new Date().toISOString() },
    ],
    posts: [
      {
        id: 1,
        content: 'Sharing circuit diagrams and thermal testing data from our latest 60A VESC drive setup. We managed to sustain 12,000 RPM on the Hardox drum weapon without thermal throttling.',
        thread_id: 1,
        user_id: 2,
        user: INITIAL_USERS[1],
        created_at: new Date(Date.now() - 1000 * 60 * 60 * 18).toISOString(),
        updated_at: new Date(Date.now() - 1000 * 60 * 60 * 18).toISOString(),
      },
    ],
  },
]

export const INITIAL_CHATROOMS: Chatroom[] = [
  {
    id: 1,
    name: 'general-robotics',
    description: 'General discussion for Prasthanam Robotics Club members',
    created_by: 1,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 60).toISOString(),
    active_users: 14,
  },
]

export const INITIAL_CHAT_MESSAGES: Record<number, ChatMessage[]> = {
  1: [
    {
      id: 101,
      chatroom_id: 1,
      user_id: 1,
      user: INITIAL_USERS[0],
      content: 'Welcome to Prasthanam Robotics Club @ GBPIET 🤖⚡',
      created_at: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
      reactions: [],
    },
  ],
}
